title: "Template"
subtitle: ""
creator: "IEEE" # E.g. the author
contributor: "" # E.g. other contributors
subject: "Fiction" # E.g. BISAC terms (https://bisg.org/page/BISACEdition) or BIC (https://ns.editeur.org/bic_categories)
description: "The Electric Book's blank template." # E.g. the blurb
publisher: "IEEE" # E.g. the publisher, imprint or brand name
publisher-url: ""
date: "2022-12-12" # YYYY-MM-DD e.g. publication date
modified: "2022-12-12" # YYYY-MM-DD e.g. date of last revision
type: "Novel" # e.g. Novel, Poetry, Memoir
identifier: "" # e.g. ISBN or UUID
source: "" # e.g. parent ISBN or ISTC
language: "en" # use ISO 639-1, 639-2, or 639-3 codes (in that order of preference)
relation: "" # e.g. other edition ISBN
coverage: "" # e.g. geographic place or chronological time span
rightsholder: "" # who owns the copyright?
rights: "All rights reserved. No part of this book may be reproduced or transmitted in any form or by any electronic or mechanical means, including photocopying and recording, or any other information storage or retrieval system, without written permission from the publisher." # e.g. a copyright statement
image: "cover.jpg"

products: # Metadata for each product for this title (only use values that override parent metadata)
  print-pdf:
    date: "2022-12-12" # YYYY-MM-DD e.g. publication or creation date
    format: "Print" # e.g. Paperback, Digital download, Digital online
    identifier: "" # e.g. ISBN or UUID
    image: "cover.jpg"
    files:
      - "0-1-titlepage"
      - "0-2-introduction"
      - "0-3-contents"
      - "01"
      - "02"
      - "03"
      - "04"
      - "05"
      - "06"
      - "07"
      - "08"
      - "09"
      - "10"
      - "11"
      - "12"
    toc: # For each menu item, include at least label and file. Optionally add id (for deep linking) and children.
      - label: "Overview"
        file: "01"
        id: "1-overview"
      - label: "Helpful resources"
        file: "02"
        id: "2-helpful-resources"
        children:
          - label: "Training and online resources"
            file: "02"
            id: "training-and-online-resources"
          - label: "Documents"
            file: "02"
            id: "documents"
      - label: "Using IEEE SA templates to write the draft"
        file: "03"
        id: "3-using-ieee-sa-templates-to-write-the-draft"
      - label: "Responsibilities of the standards committee"
        file: "04"
        id: "4-responsibilities-of-the-standards-committee"
      - label: "Copyright and permissions"
        file: "05"
        id: "5-copyright-and-permissions"
      - label: "Copyright and permissions"
        file: "05"
        id: "5-copyright-and-permissions"
        children:
          - label: "General copyright policy"
            file: "05"
            id: "general-copyright-policy"
          - label: "Excerpting material published by other organizations"
            file: "05"
            id: "excerpting-material-published-by-other-organizations"
      - label: "Patents"
        file: "06"
        id: "6-patents"
      - label: "Trademarks"
        file: "07"
        id: "7-trademarks"
      - label: "Commercial terms and conditions"
        file: "08"
        id: "8-commercial-terms-and-conditions"
      - label: "Standard language i.e., shall, should, may, and can"
        file: "09"
        id: "9-standard-language-shall-should-may-and-can"
      - label: "Additional guidance regarding language use in IEEE standards"
        file: "10"
        id: "10-additional-guidance-regarding-language-use-in-ieee-standards"
        children:
          - label: "Homogeneity"
            file: "10"
            id: "homogeneity"
          - label: "That and which"
            file: "10"
            id: "that-and-which"
          - label: "“Absolute” verbiage"
            file: "10"
            id: "absolute-verbiage"
          - label: "Use of the terms safe or safety"
            file: "10"
            id: "use-of-the-terms-safe-or-safety"
          - label: "Inclusive language"
            file: "10"
            id: "inclusive-language"
          - label: "Use of personal pronouns"
            file: "10"
            id: "use-of-personal-pronouns"
            children:
              - label: "Personal pronouns"
                file: "10"
                id: "personal-pronouns"
              - label: "Indefinite pronouns"
                file: "10"
                id: "indefinite-pronouns"
              - label: "Gender specific language"
                file: "10"
                id: "gender-specific-language"
      - label: "Frontmatter of an IEEE draft standard"
        file: "11"
        id: "11-frontmatter-of-an-ieee-draft-standard"
        children:
          - label: "General"
            file: "11"
            id: "general"
          - label: "Required frontmatter elements"
            file: "11"
            id: "required-frontmatter-elements"
            children:
              - label: "Draft labeling and designations"
                file: "11"
                id: "draft-labeling-and-designations"
              - label: "Draft copyright statements"
                file: "11"
                id: "draft-copyright-statements"
              - label: "Open Source draft statement"
                file: "11"
                id: "open-source-draft-statement"
          - label: "Title"
            file: "11"
            id: "title"
          - label: "Abstract and keywords"
            file: "11"
            id: "abstract-and-keywords"
          - label: "Participant lists"
            file: "11"
            id: "participant-lists"
          - label: "Introduction"
            file: "11"
            id: "introduction"
          - label: "Permissions list"
            file: "11"
            id: "permissions-list"
          - label: "Table of contents"
            file: "11"
            id: "table-of-contents"
      - label: "Body of an IEEE draft standard"
        file: "12"
        id: "12-body-of-an-ieee-draft-standard"
        children:
          - label: "Normative and informative clauses"
            file: "12"
            id: "normative-and-informative-clauses"
          - label: "Order of clauses"
            file: "12"
            id: "order-of-clauses"
            children:
              - label: "General"
                file: "12"
                id: "general"
              - label: "The overview of the draft"
                file: "12"
                id: "the-overview-of-the-draft"
              - label: "Scope"
                file: "12"
                id: "scope"
              - label: "Purpose"
                file: "12"
                id: "purpose"
              - label: "Word usage"
                file: "12"
                id: "word-usage"
  web:
    date: "2022-12-12" # YYYY-MM-DD e.g. publication date or last revision
    format: "Digital online" # e.g. Paperback, Digital download, Digital online
    identifier: "" # e.g. ISBN or UUID
    image: "cover.jpg"
    files:
      - "index"
      - "0-1-titlepage"
      - "0-2-copyright"
      - "0-3-contents"
      - "01": "Chapter One"
      - "02": "Chapter Two"
      
    nav: # For each menu item, include at least label and file. Optionally add id (for deep linking) and children.
      - label: "Frontmatter"
        children:
          - label: "Cover"
            file: "index"
          - label: "Title page"
            file: "0-1-titlepage"
          - label: "Copyright"
            file: "0-2-copyright"
      - label: "Contents"
        file: "0-3-contents"
      - label: "Chapter One"
        file: "01"
        id: "1-hello-world"
      - label: "Chapter Two"
        file: "02"
        id: "2-goodbye-world"
        children:
          - label: "Subsection"
            file: "02"
            id: "example-id"
    start-page: "0-3-contents" # At which file should users start reading?
    contents-page: "0-3-contents" # Your contents-page file, if you have one.
  epub:
    date: "2016-05-07" # YYYY-MM-DD e.g. publication date or last revision
    format: "Digital download" # e.g. Paperback, Digital download, Digital online
    identifier: "9780000000000" # e.g. ISBN or UUID
    image: "cover.jpg"
    start-page: "0-3-contents"
    contents-page: "0-3-contents"
    files: # add a value to any file to set any of the guide types listed in http://www.idpf.org/epub/20/spec/OPF_2.0.1_draft.htm#Section2.6
      - "0-0-cover": "cover"
      - "0-1-titlepage": "title-page"
      - "0-2-copyright": "copyright-page"
      - "0-3-contents": "toc"
      - "01": "text"
      - "02"
    toc: # For each menu item, include at least label and file (epub requires file). Optionally add id (for deep linking) and children.
      - label: "Cover"
        file: "0-0-cover"
      - label: "Title page"
        file: "0-1-titlepage"
      - label: "Copyright"
        file: "0-2-copyright"
      - label: "Contents"
        file: "0-3-contents"
      - label: "Chapter One"
        file: "01"
      - label: "Chapter Two"
        file: "02"
  screen-pdf:
    date: "2016-05-07" # YYYY-MM-DD e.g. publication date or last revision
    format: "Digital download" # e.g. Paperback, Digital download, Digital online
    identifier: "" # e.g. ISBN or UUID
    image: "cover.jpg"
    files:
      - "0-0-cover"
      - "0-1-titlepage"
      - "0-2-copyright"
      - "0-3-contents"
      - "01"
      - "02"
  app:
    date: "2016-05-07" # YYYY-MM-DD e.g. publication date or last revision
    format: "Digital download" # e.g. Paperback, Digital download, Digital online
    identifier: "" # e.g. ISBN or UUID
    image: "cover.jpg"
    files:
      - "index"
      - "0-1-titlepage"
      - "0-2-copyright"
      - "0-3-contents"
      - "01": "Chapter One"
      - "02": "Chapter Two"
    nav: # For each menu item, include at least label and file. Optionally add id (for deep linking) and children.
      - label: "Frontmatter"
        children:
          - label: "Cover"
            file: "index"
          - label: "Title page"
            file: "0-1-titlepage"
          - label: "Copyright"
            file: "0-2-copyright"
      - label: "Contents"
        file: "0-3-contents"
      - label: "Chapter One"
        file: "01"
        id: "1-hello-world"
      - label: "Chapter Two"
        file: "02"
        id: "2-goodbye-world"
        children:
          - label: "Subsection"
            file: "02"
            id: "example-id"
    start-page: "0-3-contents" # At which file should users start reading?
    contents-page: "0-3-contents" # Your contents-page file, if you have one.
